COMMENT=	rough port of Node.js's EventEmitter

MODPY_EGG_VERSION=11.1.0
DISTNAME=	pyee-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME:L}
CATEGORIES=	www
MAINTAINER =	Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

MODULES=		lang/python
MODPY_PI=		Yes
MODPY_PYBUILD =		setuptools

FLAVORS=		python3
FLAVOR=			python3

.include <bsd.port.mk>
