COMMENT =	rough port of Node.js's EventEmitter

MODPY_DISTV =	11.1.0
DISTNAME =	pyee-${MODPY_DISTV}
PKGNAME =	py-${DISTNAME:L}
CATEGORIES =	www
MAINTAINER =	Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =	lang/python
MODPY_PI =	Yes
MODPY_PYBUILD =	setuptools

.include <bsd.port.mk>
