COMMENT=		XML to Hash translator

DISTNAME=		nori-2.6.0
CATEGORIES=		textproc

HOMEPAGE=		https://github.com/savonrb/nori

MAINTAINER =		Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
