COMMENT =		provide objects with pubsub capabilities

DISTNAME =		wisper-2.0.1
CATEGORIES =		devel
HOMEPAGE =		https://github.com/krisleech/wisper
MAINTAINER =		Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE = 	ruby gem

.include <bsd.port.mk>
