COMMENT=		JSON implementation for Ruby

DISTNAME=		json_pure-2.7.2
CATEGORIES=		devel

HOMEPAGE=		http://flori.github.com/json/
MAINTAINER=		Sebastian Reitenbach <sebastia@openbsd.org>

# GPLv2
PERMIT_PACKAGE=	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
