COMMENT=		Ruby interface for GNU Readline and Edit Line

DISTNAME=		readline-ext-0.2.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/ruby/readline-ext
MAINTAINER=		Sebastian Reitenbach <sebastia@openbsd.org>

# BSD, Ruby
PERMIT_PACKAGE=	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
