# $OpenBSD$

COMMENT =		AsyncIO version of the standard multiprocessing module

MODPY_EGG_VERSION =	0.9.0
DISTNAME =		aiomultiprocess-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		devel

MAINTAINER =		Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

FLAVORS =		python3
FLAVOR =		python3

.include <bsd.port.mk>
