COMMENT =		colored symbols for various log levels for Python

MODPY_EGG_VERSION =	0.0.14
DISTNAME =		log_symbols-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		devel

MAINTAINER =		Sebastian Reitenbach <sebastia@openbsd.org>

# MIT 
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =		python3
FLAVOR =		python3

RUN_DEPENDS =	devel/py-colorama${MODPY_FLAVOR}

.include <bsd.port.mk>
