COMMENT =	C++ implementation of a fast hash map and hash set

GH_ACCOUNT =	Tessil
GH_PROJECT =	robin-map
GH_TAGNAME =	v1.2.1

CATEGORIES =	devel

HOMEPAGE =	https://tessil.github.io/robin-map/index.html
MAINTAINER =	Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		devel/cmake
USE_NINJA =		No
NO_BUILD =		Yes

.include <bsd.port.mk>
